

All: Phil Prod Read

Phil: Philosophe.c perfPhilo.sh
	./perfPhilo.sh
	
Prod: Prodcons.c perfProdcons.sh
	./perfProdcons.sh
	
Read: ReadWrite.c perfReadWrite.sh
	./perfReadWrite.sh
	
Clean: 
	rm -rf *.csv
