

All: Phil Prod Read

Phil: Philosopheaa.c perfPhiloaa.sh
	./perfPhiloaa.sh
	
Prod: Prodconsaa.c perfProdconsaa.sh
	./perfProdconsaa.sh
	
Read: ReadWriteaa.c perfReadWriteaa.sh
	./perfReadWriteaa.sh
	
Clean: 
	rm -rf *.csv
