

All: Phil Prod Read Test_and_set Test_and_test_and_set

Phil: Philosopheaa.c perfPhiloaa.sh
	./perfPhiloaa.sh
	
Prod: Prodconsaa.c perfProdconsaa.sh
	./perfProdconsaa.sh
	
Read: ReadWriteaa.c perfReadWriteaa.sh
	./perfReadWriteaa.sh
	
Test_and_set: perfTest_and_set.sh Test_and_set.c
	./perfTest_and_set.sh

Test_and_test_and_set: perfTest_and_test_and_set.sh Test_and_test_and_set.c
	./perfTest_and_test_and_set.sh

Clean: 
	rm -rf *.csv
